### PR TITLE
[redhat] explain that we use python3

### PR DESCRIPTION
**Pull request by gquintard**

### CODE REVIEW

**Comment by ingvarha** [comment]
This will work on newer fedoras and el8. It will /not/ work on el7.

I use this in my packages:

%if 0%{?rhel} == 6 || 0%{?rhel} == 7
# (lots of other stuff)
%global __python /usr/bin/python3.4
%else
%global __python %{__python3}
%endif

**Comment by Dridi** [comment]
I think the mock config takes care of defining the correct `__python` version.

We don't support el6 so we really really don't want to engage with such conditionals. I also opened an EPEL ticket a couple months ago because el7 was providing python34 but not python3 and with the upgrade to python36 that meant we couldn't have a stable dependency for the python3 package or the python3 command, I need to revisit this ticket because I have been away most of the time since I opened it.

**Comment by gquintard** [comment]
@ingvarha, the current code beg to differ :-) I needed to add that line https://github.com/varnishcache/varnish-cache/blob/master/.circleci/config.yml#L289 to get `centos:7` to build (and it does! https://circleci.com/gh/varnishcache/varnish-cache/248)

@Dridi, before adding the line, it didn't work, and after it did, but there may be other better ways

**Comment by ingvarha** [comment]
@gquintard If this works for you, your build servers may have a setting, either in mock or otherwise, that set the __python3 macro for you. It is not native to rhel7/centos7 nor to an epel7 chroot as defined in Fedora.

This macro was set at one time, but was explicitly removed again in python-rpm-macros sometime back in 2017

https://cbs.centos.org/koji/buildinfo?buildID=17030

fedora30$ rpm --eval %__python3
/usr/bin/python3

centos7$ rpm --eval %__python3
%__python3

epel7_mock_chroot# rpm --eval %__python3
%__python3

You can get around this by adding explicit BuildRequires python3 (which on el7 gives python-3.6). This works as the configure script looks around for working python variants (varnish.m4).

Ingvar

**Comment by gquintard** [comment]
@ingvarha , Nothing special about the server, it's just a `centos:7` container: https://github.com/varnishcache/varnish-cache/blob/master/.circleci/config.yml#L318

Without this PR, the packaging scripts try to create python2 bytecode for our python script, which fails

**Comment by Dridi** [comment]
I will eventually give this a try, but I have another angle to explore. Considering that we don't ship python scripts in `%{_bindir}` and that they are only part of the devel sub-package, is it even useful to pre-compile those scripts? Does it justify the performance benefits for out-of-tree VMODs?

If you are not building using the scripts from this repository, why not update the CircleCI config to define the macro there instead?

https://github.com/varnishcache/varnish-cache/blob/master/.circleci/config.yml#L395

```
rpmbuild -D '__python %{__python3}' --rebuild "$RESULT_DIR"/varnish-*.src.rpm
```

I'm also wondering why the brp script tries to compile scripts with python2 when they have a python3 shebang. We should probably disable it since it doesn't help much in the first place...

**Comment by gquintard** [comment]
> `rpmbuild -D '__python %{__python3}' --rebuild "$RESULT_DIR"/varnish-*.src.rpm`

I can work with that if you think that's the best place to deal with it. I'll close these PRs

**Pull request closed without merging**
