### PR TITLE
Allow VCL auto-discard when reloading

### PR DESCRIPTION
**Pull request by gauthier-delacroix**
Here's a patch I've submitted a while ago in the mailing list, but that hasn't been followed after I've applied change request.

It allows to automatically discard old VCL configs when reloading, instead of keeping them all. It is possible to keep a fixed number of old configs.

As it was initially done for v4.0, it doesn't take cold/warm configs into account.

Initial submit: https://www.varnish-cache.org/lists/pipermail/varnish-dev/2014-November/008073.html
Change request: https://www.varnish-cache.org/lists/pipermail/varnish-dev/2014-December/008121.html
Last submit: https://www.varnish-cache.org/lists/pipermail/varnish-dev/2015-June/008360.html

### CODE REVIEW

**Comment by joshuaspence** [comment]
+1

**Comment by joshuaspence** [comment]
I guess this patch should also be applied to Debian?

**Comment by Dridi** [comment]
@gauthier-delacroix: thanks for re-submitting, it looks OK although it could probably be simplified a bit.

@joshuaspence: we have discussed with @denisbr the possibility to maintain a single reload script for all platforms. That would positively answer your question.

**Comment by Dridi** [comment]
I'd love if you could try #70 that has auto-discard in place.

**Comment by Dridi** [comment]
Closing in favor of #70.

**Pull request closed without merging**
