### PR TITLE
debian/control depends on python3

### PR DESCRIPTION
**Pull request by dmatetelki**

### CODE REVIEW

**Comment by Dridi** [comment]
Meh, I'm already running local builds of packaging updated to require python 3 :(

**Comment by Dridi** [comment]
To be clear, the thing I'm not happy about is that they block IRC where I am today and that would have avoided duplication of effort.

**Comment by dmatetelki** [comment]
@Dridi : I don't understand. Shall i merge it or not? The schroot will fail without it.

Also, they block IRC? You mean your Internet Relay Chat client conflicts with python3? :confused:

**Comment by Dridi** [comment]
No, the office I'm in today blocks IRC so I was not able to let you know I was working on this.

Also, your patch does not work when I try to build it. I have fixed the RPM side of things locally and am close to fixing the DPKG side too.

**Comment by Dridi** [comment]
See #124, what I was also working on...

**Comment by dmatetelki** [comment]
Closing in favor of #124

**Pull request closed without merging**
