### PR TITLE
Missed out changes.rst from redhat

### PR DESCRIPTION
**Pull request by dmatetelki**

### CODE REVIEW

**Comment by Dridi** [comment]
The line `%doc doc/changes*.html` refers to nothing I'm aware of, I think it was meant to be RST in the first place.

Please change the patch to this:

```diff
-%doc doc/changes*.html
+%doc doc/changes*.rst
```

Please note that I kept the `*` in the path.

**Comment by dmatetelki** [comment]
We do have a `changes.html`, generated from the `changes.rst`:

https://github.com/varnishcache/varnish-cache/blob/master/doc/Makefile.am#L7-L15

Thou I wonder why do we need the same information in 2 files in different formats.
Maybe it should be a part of /doc/html ?

**Comment by Dridi** [comment]
Oh right, it's part of the dist archive, so we probably don't need the RST if we already have the HTML changelog.

**Comment by dmatetelki** [comment]
done

**Pull request merged**
